#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2021 KOOMOX <koomoxs@gmail.com>
# 
# <https://github.com/koomox/openwrt>
#

name: Build RPi 3B+ OpenWrt

on:
  push:
    branches: 
      - main
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

env:
  REPO_URL: https://github.com/Lienol/openwrt.git
  REPO_BRANCH: 21.02
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: rpi3b.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  DEVICE_NAME: _bcm2710_rpi3b_plus
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android /opt/ghc
          sudo -E apt-get update -y
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 curl gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Clone source code
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: Load custom feeds
        run: |
          [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
          chmod +x ./$DIY_P1_SH && ./$DIY_P1_SH

      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x ./$DIY_P2_SH && ./$DIY_P2_SH

      - name: Download package
        run: |
          cd $GITHUB_WORKSPACE/openwrt
          make defconfig
          make -j8 download V=s
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        run: |
          cd $GITHUB_WORKSPACE/openwrt
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s

      - name: Check space usage
        run: |
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -hT
          echo "======================="

      - name: Prepare artifact
        run: |
          cd $GITHUB_WORKSPACE/openwrt/bin/targets/*/*
          rm -rf packages
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}
